# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 10:43
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='T\xedtulo')),
                ('ediction', models.CharField(max_length=65, verbose_name='Local de Edi\xe7\xe3o')),
                ('edictor', models.CharField(max_length=80, verbose_name='Editora')),
                ('date_ediction', models.DateField(default=datetime.date(2016, 9, 12), verbose_name='Data de Edi\xe7\xe3o')),
                ('status', models.CharField(default='disponivel', max_length=65, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lending', models.DateField(default=datetime.date(2016, 9, 12), verbose_name='Data do empr\xe9stimo')),
                ('date_devolution', models.DateField(blank=True, default=datetime.date(2016, 9, 12), verbose_name='Data de devolu\xe7\xe3o')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to='library_sparks.Book', verbose_name='livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendings', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reserve', models.DateField(default=datetime.date(2016, 9, 12), verbose_name='Data da Reserva')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='library_sparks.Book', verbose_name='livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
