# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 11:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('library_sparks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_ediction',
            field=models.DateField(default=datetime.datetime(2016, 9, 12, 11, 4, 13, 120630, tzinfo=utc), verbose_name='Data de Edi\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='date_devolution',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 9, 12, 11, 4, 13, 124348, tzinfo=utc), verbose_name='Data de devolu\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='lending',
            name='date_lending',
            field=models.DateField(default=datetime.datetime(2016, 9, 12, 11, 4, 13, 124178, tzinfo=utc), verbose_name='Data do empr\xe9stimo'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='date_reserve',
            field=models.DateField(default=datetime.datetime(2016, 9, 12, 11, 4, 13, 128397, tzinfo=utc), verbose_name='Data da Reserva'),
        ),
    ]
